### PR TITLE
WIP: Implement basic referral reward system

### PR DESCRIPTION
**Pull request by bruno-dtravel**
Remaining tasks:

- [ ] Tests

### CODE REVIEW

**Comment by jacky-dtravel** [comment]
@bruno-dtravel , the document, that you shared above, links to another document for [Booking Referral Rewards](https://docs.google.com/document/d/1S_P5pm9FfbqvEoC9HuOxPoWFVo7597dQoQciQ-LUhyc/edit#heading=h.lwdzow4ofy1p), this one is still private, I cannot access it. Has this document finalized yet? Can you grant access for me (jacky@dtravel.com)?

**Comment by Perito-Moreno** [comment]
Hi @jacky-dtravel . I have just made the document visible to anyone within dtravel. Could you check whether you can access it now?

**Comment by jacky-dtravel** [comment]
Thank you @bruno-dtravel

**Comment by jacky-dtravel** [comment]
Hi @bruno-dtravel , I created #38 to re-implement this PR for new booking contract v2. If you are OK, I will close this PR.

**Comment by Zahnentferner** [comment]
@jacky-dtravel , yes, let's close this one.

In the future, I think it is better to merge and deal with merge conflicts than to re-implement.

**Comment by jacky-dtravel** [comment]
Thank you @bruno-dtravel

**Pull request closed without merging**
